name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install KiCAD v5
      run: |
        sudo add-apt-repository --yes ppa:js-reynaud/kicad-5.1
        sudo apt update
        sudo apt install --install-recommends kicad

    - name: Run a one-line script
      run: python test.py
