name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install KiCAD v5
      run: |
        add-apt-repository --yes ppa:js-reynaud/kicad-5.1
        apt update
        apt install --install-recommends kicad

    - name: Run a one-line script
      run: |
        python -V
        python test.py
